#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# Removes all files found in the build directories. It asks no questions as to
# how or why the files got there. Be especially careful with the 'bash'
# directory if you have authored scripts for release, add a `bash🖉`
# directory instead of putting them in `bash`.

cd "$REPO_HOME"/developer || exit 1
source tool🖉/env_script

# remove example class files

  cd example || exit 1

  for file in Example_*.class; do
    echo "file: " $file
    rm_na "$file"
    wrapper_name=$(basename "$file" .class)
    rm_na "$wrapper_name"
  done

echo "$(script_fn) done."

