#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# Removes all files found in the build directories. It asks no questions as to
# how or why the files got there. Be especially careful with the 'bash'
# directory if you have authored scripts for release, add a `bash🖉`
# directory instead of putting them in `bash`.

cd "$REPO_HOME"/developer || exit 1
source tool🖉/env_script

set -x

# remove main build files

  # rm_na currently does not handle links correctly 
  rm -rf scratchpad/*
  rm_na -f jvm/*
  rm_na -f bash/*

set +x

echo "$(script_fn) done."

