#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# Removes all files found in the build directories. It asks no questions as to
# how or why the files got there. Be especially careful with the 'bash'
# directory if you have authored scripts for release, add a `bash🖉`
# directory instead of putting them in `bash`.

# input guards
  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

set -x

# remove main build files

  cd "$REPO_HOME"/developer

  # rm_na currently does not handle links correctly 
  rm -r scratchpad/*

  rm_na jvm/*
  rm_na bash/*


# remove example class files

  rm_na example/*.class

set +x

echo "$(script_fn) done."

