#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer/example

echo "Compiling example .java files..."

  set -x
  javac -g -sourcepath . *.java
  set +x

  if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
  fi

echo "Creating bash wrappers..."

set -x

wrapper=(Example_*.class)

for file in "${wrapper[@]}"; do
  wrapper_name=$(basename "$file" .class)
  cat > "$wrapper_name" << EOL
#!/bin/bash
java $wrapper_name
EOL

  # Make the wrapper executable
  chmod +x "$wrapper_name"
done

set +x

echo "$(script_fp) done."

