#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

cd "$REPO_HOME"/developer || exit 1
source tool🖉/env_script


cd example || exit 1

echo "Compiling example .java files..."

  set -x
  javac -g -sourcepath . *.java
  set +x

  if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
  fi

echo "Creating bash wrappers..."

  for file in Example_*.class; do
    echo "file: " $file
    wrapper_name=$(basename "$file" .class)
    cat > "$wrapper_name" << EOL
#!/bin/bash
java $wrapper_name
EOL
    # Make the wrapper executable
    chmod +x "$wrapper_name"
    done

echo "$(script_fp) done."

