#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

cd "$REPO_HOME"/developer || exit 1
source tool🖉/env_script

echo "Compiling files..."
  set -x
  javac -Xlint:unchecked -g -d scratchpad javac🖉/*.java
  set +x
  if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
  fi

echo "Creating JAR file..."
  set -x
  jar_file=jvm/"$PROJECT".jar
  mkdir -p jvm
  jar cf $jar_file -C scratchpad .
  set +x
  if [ $? -eq 0 ]; then
    echo "JAR file created successfully: $jar_file"
  else
    echo "Failed to create JAR file."
    exit 1
  fi

echo "Creating bash wrappers..."
  mkdir -p bash
  wrapper=$(bash_wrapper_list)
  for file in "${wrapper[@]}"; do
    cat > bash/$file << EOL
#!/bin/bash
java com.ReasoningTechnology."$PROJECT".$file
EOL
    chmod +x bash/$file
  done

echo "$(script_fp) done."

