#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/developer


echo "Compiling example .java files..."

  set -x
  cd example
  javac -verbose -g -sourcepath . *.java
  set +x
  if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
  fi

echo "Creating bash wrappers..."
  # wrapper is a space separated list
  wrapper=Example_*.class
  for file in $wrapper;do
    cat > $file << EOL
#!/bin/bash
java $file
EOL
    chmod +x $file
  done

echo "$(script_fp) done."

