#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# before running this script, gather everything needed for the release on the scratchpad

cd "$REPO_HOME"/developer || exit 1
source tool🖉/env_script

# Inform the user

  echo "The pwd for this script is `pwd`."

# we build into the scratchpad

  if [ ! -d scratchpad ]; then
    echo "$(script_fp):: no scratchpad directory"
    exit 1
  fi


# Function to copy and set permissions

  install_file() {
    source_fp="$1"
    target_dp="$2"
    perms="$3"

    target_file="$target_dp/$(basename "$source_fp")"

    if [ ! -f "$source_fp" ]; then
      echo "install_file:: Source file '$source_fp' does not exist."
      return 1
    fi

    if ! install -m "$perms" "$source_fp" "$target_file"; then
      echo "Error: Failed to install $(basename "$source_fp") to $target_dp"
      exit 1
    else
      echo "Installed $(basename "$source_fp") to $target_dp with permissions $perms"
    fi
  }

# scratchpad --> .jar file 

  mkdir -p jvm
  jar_file=$(realpath jvm/"$PROJECT".jar)

  pushd scratchpad

  echo "scratchpad -> $jar_file"
  jar cf $jar_file *
  if [ $? -ne 0 ]; then
    echo "Failed to create $jar_file file."
    exit 1
  fi

  popd

# move files to the release dir

  release_dir="$REPO_HOME/release"
  bash_dir="$REPO_HOME/developer/bash"
  wrapper=$(bash_wrapper_list)

  install_file "$jar_file" "$release_dir" "ug+r"

  for wrapper in $wrapper; do
    install_file "$bash_dir"/"$wrapper" "$release_dir" "ug+r+x"
  done

echo "$(script_fp) done."
