#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards
env_must_be="tester/tool🖉/env"
if [ "$ENV" != "$env_must_be" ]; then
  echo "$(script_fp):: error: must be run in the $env_must_be environment"
  exit 1
fi

# space separated list of bash interface wrappers
echo \
  Test_File_0 \
  Test_Label_0 \
  Test_LabelList_0 \
  Test_Node_0 \
  Test_NodeList_0 \
  Test_Token_0 \
  Test_TokenSet_0 \
  Test_Util_0 \
  Test_Graph_0 \
  ""

 
