#!/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards
env_must_be="tester/tool🖉/env"
if [ "$ENV" != "$env_must_be" ]; then
  echo "$(script_fp):: error: must be run in the $env_must_be environment"
  exit 1
fi

# space separated list of bash interface wrappers
echo \
  File_0 \
  Label_0 \
  LabelList_0 \
  Node_0 \
  NodeList_0 \
  Token_0 \
  TokenSet_0 \
  Util_0 \
""

 
