#!/bin/bash
# remove  all files created by make's call to `javac`

script_name=$(basename ${BASH_SOURCE[0]})
if [ -z "$REPO_HOME" ]; then
  echo "$script_name:: REPO_HOME is not set."
  exit 1
fi
if [ -z "$ENV_DEVELOPER_LOCAL" ]; then
  echo "release:: ENV_DEV_BUILD is not set."
  exit 1
fi

set -x
cd "$REPO_HOME"/developer
rm -rf scratch_pad/*
set +x

echo "$script_name done."
