#!/bin/bash
# remove file made by `make` and by `release`

script_name=$(basename ${BASH_SOURCE[0]})
error=false
if [ -z "$REPO_HOME" ]; then
  echo "$script_name:: REPO_HOME is not set."
  error=true
fi
if [ -z "$ENV_DEVELOPER_LOCAL" ]; then
  echo "$script_name:: ENV_DEV_BUILD is not set."
  error=true
fi
if [ error ]; then
  exit 1
fi

# Define release directory
release_dir="$REPO_HOME"/release_candidate
wrapper=build

set -x
cd "$REPO_HOME"/developer
rm -rf scratch_pad/*
rm -f jvm/Ariadne.jar
rm -f shell/"$wrapper"
rm -f "$release_dir"/Ariadne.jar
rm -f "$release_dir"/{$wrapper}
set +x

echo "$script_name done."
