#!/bin/bash

# Ensure REPO_HOME and ENV_DEV_BUILD are set
if [ -z "$REPO_HOME" ]; then
  echo "release:: REPO_HOME is not set."
  exit 1
fi

if [ -z "$ENV_DEV_BUILD" ]; then
  echo "release:: ENV_DEV_BUILD is not set."
  exit 1
fi

# Define release directory
release_dir="$REPO_HOME"/release_candidate
wrapper=build

set -x
cd "$REPO_HOME"/developer
rm -rf scratch_pad/*
rm -f jvm/Ariadne.jar
rm -f shell/"$wrapper"
rm -f "$release_dir"/Ariadne.jar
rm -f "$release_dir"/{$wrapper}
set +x

echo "clean_dist complete."
