#!/bin/env bash

script_name=$(basename ${BASH_SOURCE[0]})
if [ -z "$ENV_TESTER_LOCAL" ]; then
  echo "make.sh:: script can only be run in the tester  environment"
  env_error=true
fi




echo "$script_name done."
