#!/bin/env bash

# input guards

  env_must_be="tester/tool/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

# the build
set -x

  cd $REPO_HOME/tester

  javac -d scratch_pad javac/TestBench.java
  jar cf jvm/TestBench.jar -C scratch_pad .

set +x

echo "$(script_fp) done."
